# Shared helpers for the Out of the Vortex build/release tools.
# Compatible with Windows 8 and up
# Requires git (used to apply/create patches).

$ErrorActionPreference = 'Stop'

# Known-good identities (SHA-256, uppercase hex).
$OOTV = @{
    # Hidden Palace source archive: Out_of_the_Vortex_(Source_Code_-_Sep_13,_1995).zip
    SourceZipSha   = 'D2A1F27174B3A1B27CF347A85AB4C731D200A92A9BB363526F49910C461CBD5A'
    # Archive TOTAL2.68K as shipped inside that archive
    ArchiveTotal2 = 'C4E75EF03C298B67A6F445C492935EFDD13BB6065259C80192E90C6B21658479'
    # axm68k.exe ("SN 68k version 2.53"), github.com/cvghivebrain/axm68k
    Axm68kSha      = '29AB2945555FAE2903A44FF516BAFA486B61C3AA1A14B6D20139FE295D777DE5'
    # The sources hardcode this directory in every include/incbin path
    CanonicalPath  = 'c:\travaux\megadrv\vortex2'
    MacrosName     = 'Macros - More CPUs.asm'
}

function Get-Sha256([string]$Path) {
    # .NET directly rather than Get-FileHash to support Windows 8.
    $full = (Resolve-Path -LiteralPath $Path).ProviderPath
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $fs = [System.IO.File]::OpenRead($full)
    try { [System.BitConverter]::ToString($sha.ComputeHash($fs)) -replace '-', '' }
    finally { $fs.Dispose(); $sha.Dispose() }
}

function Assert-Sha256([string]$Path, [string]$Expected, [string]$What) {
    $h = Get-Sha256 $Path
    if ($h -ne $Expected.ToUpper()) {
        throw "$What checksum mismatch:`n  file     $Path`n  expected $Expected`n  actual   $h"
    }
    Write-Host "  OK  $What verified (SHA-256)" -ForegroundColor Green
}

function Assert-Git {
    try { $null = & git --version } catch {
        throw 'git is required (it applies and creates the patches). Install Git for Windows, then retry.'
    }
}

# What the current patch set is expected to build. Generated by
# make-release.ps1 on versioned runs - the hash of what a release actually
# proved, not a hand-maintained constant (so it cannot drift when a new
# patch ships).
function Get-ExpectedRom([string]$PatchRoot) {
    $f = Join-Path $PatchRoot 'expected-rom.txt'
    if (-not (Test-Path -LiteralPath $f)) {
        throw "missing $f - it ships with the repository and is regenerated by make-release.ps1"
    }
    $h = @{}
    foreach ($line in Get-Content -LiteralPath $f) {
        $parts = $line -split '\s+', 2
        if ($parts.Count -eq 2) { $h[$parts[0]] = $parts[1].Trim() }
    }
    @{ Version = $h['version']; Sha256 = $h['sha256'].ToUpper(); Bytes = [long]$h['bytes'] }
}

# Numbered per-fix patch files (01-*.patch, 02-*.patch, ...), numeric order.
# latest.patch is excluded by the ^\d\d- filter.
function Get-PatchFiles([string]$PatchRoot) {
    Get-ChildItem -LiteralPath $PatchRoot -Filter *.patch |
        Where-Object { $_.Name -match '^\d\d-' } |
        Sort-Object Name
}

function Invoke-ApplyPatch([string]$TreeDir, [string]$PatchFile) {
    Push-Location -LiteralPath $TreeDir
    try {
        & git -c core.autocrlf=false apply --whitespace=nowarn "$PatchFile"
        if ($LASTEXITCODE -ne 0) { throw "git apply failed for $PatchFile" }
        Write-Host ('  OK  applied {0}' -f (Split-Path $PatchFile -Leaf)) -ForegroundColor Green
    } finally { Pop-Location }
}

# The archive sources reference c:\travaux\megadrv\vortex2 in 620 include/incbin
# paths (mixed case). When the tree lives anywhere else, rewrite them. Latin-1
# round-trips every byte value, so the cp850 text is never corrupted.
function Invoke-RedirectPaths([string]$TreeDir, [string]$NewPath) {
    $enc = [System.Text.Encoding]::GetEncoding(28591)
    $total = 0
    foreach ($name in 'TOTAL2.68K', 'HEADER.68K', 'REPLAY.68K') {
        $p = Join-Path $TreeDir $name
        $text = $enc.GetString([System.IO.File]::ReadAllBytes($p))
        $rx = [regex]'(?i)[a-z]:\\travaux\\megadrv\\vortex2'
        $total += $rx.Matches($text).Count
        [System.IO.File]::WriteAllBytes($p, $enc.GetBytes($rx.Replace($text, $NewPath.TrimEnd('\'))))
    }
    Write-Host "  OK  $total include/incbin paths redirected to $NewPath" -ForegroundColor Green
}

function Invoke-Assemble([string]$TreeDir, [string]$Axm68k) {
    Push-Location -LiteralPath $TreeDir
    try {
        if (Test-Path 'TOTAL2.bin') { Remove-Item 'TOTAL2.bin' -Force }
        $out = & $Axm68k /p /c /zd /k /ov+ /ol+ 'TOTAL2.68K,TOTAL2.bin,TOTAL2.symb,TOTAL2.list'
        $txt = ($out | Out-String)
        Write-Host $txt
        if (-not (Test-Path 'TOTAL2.bin')) { throw 'assembly produced no TOTAL2.bin - see assembler output above' }
        if ($txt -match '(\d+)\s+errors?' -and [int]$Matches[1] -gt 0) { throw 'assembler reported errors' }
    } finally { Pop-Location }
    Join-Path $TreeDir 'TOTAL2.bin'
}

# Locate the game directory (the one holding TOTAL2.68K) under an extracted archive.
function Find-GameTree([string]$Root) {
    $hit = Get-ChildItem -LiteralPath $Root -Recurse -Filter 'TOTAL2.68K' | Select-Object -First 1
    if (-not $hit) { throw "TOTAL2.68K not found under $Root - is this the Hidden Palace source archive?" }
    $hit.Directory.FullName
}
